var nombre = prompt("Ingrese su nombre")
//console.log("Hola" + nombre)
var apellido = prompt("Ingrese su apellido")
alert("Bienvenido " + nombre + " " + apellido)
//console.log("Bienvenido " + nombre + " " + apellido)
